spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://users:8081
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: food-service
          uri: http://food:8082
          predicates:
            - Path=/food/**
          filters:
            - StripPrefix=1
